ENodeMicro/EQueue.AdminWeb/Models/SetQueueNextConsumeOffsetViewModel.cs
namespace EQueue.AdminWeb.Models
{
    public class SetQueueNextConsumeOffsetViewModel
    {
        public string ConsumerGroup { get; set; }
        public string Topic { get; set; }
        public int QueueId { get; set; }
        public long NextOffset { get; set; }
    }
}

ENodeMicro/EQueue.AdminWeb/Controllers/BrokerController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using EQueue.AdminWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace EQueue.AdminWeb.Controllers
{
    public class BrokerController : Controller
    {
        private MessageService _messageService;

        public BrokerController(MessageService messageService)
        {
            _messageService = messageService;
        }

        public async Task<ActionResult> Index(string clusterName, string brokerName)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var result = await _messageService.QueryBrokerStatisticInfo(clusterName, brokerName);
            return View(result);
        }
        public async Task<ActionResult> QueueInfoList(string clusterName, string brokerName, string topic)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var topicQueueInfoList = await _messageService.GetTopicQueueInfoList(clusterName, brokerName, topic);
            return View(new BrokerTopicQueueListViewModel
            {
                Topic = topic,
                TopicQueueInfoList = topicQueueInfoList
            });
        }
        public async Task<ActionResult> ConsumeInfoList(string clusterName, string brokerName, string group, string topic)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var topicConsumeInfoList = await _messageService.GetTopicConsumeInfoList(clusterName, brokerName, group, topic);
            return View(new BrokerTopicConsumeListViewModel
            {
                Group = group,
                Topic = topic,
                TopicConsumeInfoList = topicConsumeInfoList
            });
        }
        public async Task<ActionResult> ProducerList(string clusterName, string brokerName, string group, string topic)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var producerList = await _messageService.GetProducerInfoList(clusterName, brokerName);
            return View(new BrokerProducerListViewModel
            {
                ProducerList = producerList
            });
        }
        public async Task<ActionResult> ConsumerList(string clusterName, string brokerName, string group, string topic)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var consumerList = await _messageService.GetConsumerInfoList(clusterName, brokerName, group, topic);
            return View(new BrokerConsumerListViewModel
            {
                Group = group,
                Topic = topic,
                ConsumerList = consumerList
            });
        }
        public async Task<ActionResult> LatestSendMessages(string clusterName, string brokerName)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var messageList = await _messageService.GetLatestSendMessagesList(clusterName, brokerName);
            var messageInfoList = new List<MessageInfo>();

            foreach (var message in messageList)
            {
                string[] array = message.Split('_');
                var messageId = array[0];
                var createTime = new DateTime(long.Parse(array[1]));
                var storedTime = new DateTime(long.Parse(array[2]));
                messageInfoList.Add(new MessageInfo
                {
                    MessageId = messageId,
                    CreateTime = createTime,
                    StoredTime = storedTime
                });
            }
            messageInfoList.Sort((x, y) =>
            {
                if (x.StoredTime.Ticks > y.StoredTime.Ticks)
                {
                    return -1;
                }
                else if (x.StoredTime.Ticks < y.StoredTime.Ticks)
                {
                    return 1;
                }
                return 0;
            });

            var sequence = 1;
            foreach (var messageInfo in messageInfoList)
            {
                messageInfo.Sequence = sequence++;
            }
            return View(new BrokerLatestMessageIdListViewModel
            {
                MessageInfoList = messageInfoList
            });
        }
        public async Task<ActionResult> CreateTopic(string clusterName, string brokerName, string topic, int? initialQueueCount)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            await _messageService.CreateTopic(clusterName, brokerName, topic, initialQueueCount ?? 4);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Topic = topic });
        }
        public async Task<ActionResult> DeleteTopic(string clusterName, string brokerName, string topic)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            await _messageService.DeleteTopic(clusterName, brokerName, topic);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Topic = topic });
        }
        public async Task<ActionResult> AddQueue(string clusterName, string brokerName, string topic)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            await _messageService.AddQueue(clusterName, brokerName, topic);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Topic = topic });
        }
        public async Task<ActionResult> DeleteQueue(string clusterName, string brokerName, string topic, int queueId)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            await _messageService.DeleteQueue(clusterName, brokerName, topic, queueId);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Topic = topic });
        }
        public async Task<ActionResult> SetQueueProducerVisible(string clusterName, string brokerName, string topic, int queueId, bool visible)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            await _messageService.SetQueueProducerVisible(clusterName, brokerName, topic, queueId, visible);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Topic = topic });
        }
        public async Task<ActionResult> SetQueueConsumerVisible(string clusterName, string brokerName, string topic, int queueId, bool visible)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            await _messageService.SetQueueConsumerVisible(clusterName, brokerName, topic, queueId, visible);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Topic = topic });
        }
        [HttpGet]
        public ActionResult SetQueueNextConsumeOffset(string clusterName, string brokerName, string consumerGroup, string topic, int queueId)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var model = new SetQueueNextConsumeOffsetViewModel
            {
                ConsumerGroup = consumerGroup,
                Topic = topic,
                QueueId = queueId
            };
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> SetQueueNextConsumeOffset(string clusterName, string brokerName, string consumerGroup, string topic, int queueId, long nextOffset)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            await _messageService.SetQueueNextConsumeOffset(clusterName, brokerName, consumerGroup, topic, queueId, nextOffset);
            return RedirectToAction("ConsumeInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Group = consumerGroup, Topic = topic });
        }
        public async Task<ActionResult> DeleteConsumerGroup(string clusterName, string brokerName, string consumerGroup)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            await _messageService.DeleteConsumerGroup(clusterName, brokerName, consumerGroup);
            return RedirectToAction("ConsumeInfoList", new { ClusterName = clusterName, BrokerName = brokerName });
        }
    }
}

ENodeMicro/EQueue.AdminWeb/Views/Home/BrokerList.cshtml
@model EQueue.AdminWeb.Models.ClusterBrokerListViewModel
@{
    ViewBag.Title = "BrokerList";
}
<div>
    @using (Html.BeginForm("BrokerList", "Home", new { clusterName = ViewBag.ClusterName, brokerName = ViewBag.BrokerName }, FormMethod.Post, null, new { @class = "form-inline", role = "form" }))
    {
        <div class="form-group">
            <label class="sr-only" for="ClusterName"></label>
            @Html.TextBoxFor(m => m.ClusterName, new { @class = "form-control", placeholder = "ClusterName" })
        </div>
        <button type="submit" class="btn btn-default">查询</button>
    }
    <table class="table table-striped">
        <thead>
            <tr>
                <th width="13%" class="vertical-center">
                    GroupName
                </th>
                <th width="13%" class="vertical-center">
                    BrokerName
                </th>
                <th width="8%" class="vertical-center">
                    BrokerRole
                </th>
                <th width="12%" class="vertical-center">
                    ProducerAddress
                </th>
                <th width="12%" class="vertical-center">
                    ConsumerAddress
                </th>
                <th width="12%" class="vertical-center">
                    AdminAddress
                </th>
                <th width="7%" class="vertical-center">
                    发送TPS
                </th>
                <th width="7%" class="vertical-center">
                    消费TPS
                </th>
                <th width="10%" class="vertical-center">
                    总堆积数
                </th>
                <th width="8%" class="vertical-center">
                    操作
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.BrokerList)
            {
                var broker = item.BrokerInfo;
                <tr>
                    <td class="vertical-center">
                        @broker.GroupName
                    </td>
                    <td class="vertical-center">
                        @broker.BrokerName
                    </td>
                    <td class="vertical-center">
                        @broker.BrokerRole
                    </td>
                    <td class="vertical-center">
                        @broker.ProducerAddress
                    </td>
                    <td class="vertical-center">
                        @broker.ConsumerAddress
                    </td>
                    <td class="vertical-center">
                        @broker.AdminAddress
                    </td>
                    <td class="vertical-center">
                        @item.TotalSendThroughput
                    </td>
                    <td class="vertical-center">
                        @item.TotalConsumeThroughput
                    </td>
                    <td class="vertical-center">
                        @item.TotalUnConsumedMessageCount
                    </td>
                    <td class="vertical-center">
                        @Html.ActionLink("查看", "Index", "Broker", new { clusterName = broker.ClusterName, brokerName = broker.BrokerName }, null)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

ENodeMicro/EQueue.AdminWeb/Views/Home/ConsumeInfoList.cshtml
@model EQueue.AdminWeb.Models.ClusterTopicConsumeListViewModel
@{
    ViewBag.Title = "ConsumeInfoList";
}
<div>
    @using (Html.BeginForm("ConsumeInfoList", "Home", new { clusterName = ViewBag.ClusterName }, FormMethod.Post, null, new { @class = "form-inline", role = "form" }))
    {
        <div class="form-group">
            <label class="sr-only" for="ClusterName"></label>
            @Html.TextBoxFor(m => m.ClusterName, new { @class = "form-control", placeholder = "ClusterName" })
        </div>
        <div class="form-group">
            <label class="sr-only" for="Group"></label>
            @Html.TextBoxFor(m => m.Group, new { @class = "form-control", placeholder = "Group" })
        </div>
        <div class="form-group">
            <label class="sr-only" for="Topic"></label>
            @Html.TextBoxFor(m => m.Topic, new { @class = "form-control", placeholder = "Topic" })
        </div>
        <button type="submit" class="btn btn-default">查询</button>
    }
    <table class="table table-striped">
        <thead>
            <tr>
                <th width="10%" class="vertical-center">
                    BrokerName
                </th>
                <th width="10%" class="vertical-center">
                    ConsumerGroup
                </th>
                <th width="10%" class="vertical-center">
                    Topic
                </th>
                <th width="5%" class="text-center vertical-center">
                    QueueId
                </th>
                <th width="10%" class="text-center vertical-center">
                    CurrentOffset
                </th>
                <th width="10%" class="text-center vertical-center">
                    消费进度
                </th>
                <th width="10%" class="text-center vertical-center">
                    堆积数
                </th>
                <th width="10%" class="text-center vertical-center">
                    CacheCount
                </th>
                <th width="10%" class="text-center vertical-center">
                    消费者个数
                </th>
                <th width="10%" class="text-center vertical-center">
                    消费TPS
                </th>
                <th width="5%" class="vertical-center">
                    操作
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.TopicConsumeInfoList)
            {
                foreach (var item in line.TopicConsumeInfoList)
                {
                    <tr>
                        <td class="vertical-center">
                            @Html.ActionLink(@line.BrokerInfo.BrokerName, "Index", "Broker", new { clusterName = ViewBag.ClusterName, brokerName = @line.BrokerInfo.BrokerName }, null)
                        </td>
                        <td class="vertical-center">
                            @item.ConsumerGroup
                        </td>
                        <td class="vertical-center">
                            @item.Topic
                        </td>
                        <td class="text-center vertical-center">
                            @item.QueueId
                        </td>
                        <td class="text-center vertical-center">
                            @item.QueueCurrentOffset
                        </td>
                        <td class="text-center vertical-center">
                            @item.ConsumedOffset
                        </td>
                        <td class="text-center vertical-center">
                            @item.QueueNotConsumeCount
                        </td>
                        <td class="text-center vertical-center">
                            @item.ClientCachedMessageCount
                        </td>
                        <td class="text-center vertical-center">
                            @item.OnlineConsumerCount
                        </td>
                        <td class="text-center vertical-center">
                            @item.ConsumeThroughput
                        </td>
                        <td class="vertical-center">
                            <div class="dropdown">
                                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                                    操作
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li>
                                        @Html.ActionLink("设置队列消费进度", "SetQueueNextConsumeOffset", new { clusterName = ViewBag.ClusterName, consumerGroup = item.ConsumerGroup, topic = item.Topic, queueId = item.QueueId })
                                    </li>
                                    @if (item.OnlineConsumerCount == 0)
                                    {
                                        <li>
                                            @Html.ActionLink("删除消费者分组", "DeleteConsumerGroup", new { clusterName = ViewBag.ClusterName, consumerGroup = item.ConsumerGroup })
                                        </li>
                                    }
                                </ul>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

ENodeMicro/EQueue.AdminWeb/Views/Home/ConsumerList.cshtml
@model EQueue.AdminWeb.Models.ClusterConsumerListViewModel
@{
    ViewBag.Title = "ConsumerList";
}
<div>
    @using (Html.BeginForm("ConsumerList", "Home", new { clusterName = ViewBag.ClusterName }, FormMethod.Post, null, new { @class = "form-inline", role = "form" }))
    {
        <div class="form-group">
            <label class="sr-only" for="ClusterName"></label>
            @Html.TextBoxFor(m => m.ClusterName, new { @class = "form-control", placeholder = "ClusterName" })
        </div>
        <div class="form-group">
            <label class="sr-only" for="Group"></label>
            @Html.TextBoxFor(m => m.Group, new { @class = "form-control", placeholder = "Group" })
        </div>
        <div class="form-group">
            <label class="sr-only" for="Topic"></label>
            @Html.TextBoxFor(m => m.Topic, new { @class = "form-control", placeholder = "Topic" })
        </div>
        <button type="submit" class="btn btn-default">查询</button>
    }
    <table class="table table-striped">
        <thead>
            <tr>
                <th width="10%" class="vertical-center">
                    ConsumerGroup
                </th>
                <th width="20%" class="vertical-center">
                    ConsumerId
                </th>
                <th width="10%" class="vertical-center">
                    BrokerName
                </th>
                <th width="10%" class="vertical-center">
                    Topic
                </th>
                <th width="10%" class="text-center vertical-center">
                    QueueId
                </th>
                <th width="10%" class="text-center vertical-center">
                    CurrentOffset
                </th>
                <th width="10%" class="text-center vertical-center">
                    消费进度
                </th>
                <th width="10%" class="text-center vertical-center">
                    堆积数
                </th>
                <th width="10%" class="text-center vertical-center">
                    CacheCount
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ConsumerList)
            {
                <tr>
                    <td class="vertical-center">
                        @item.ConsumerInfo.ConsumerGroup
                    </td>
                    <td class="vertical-center">
                        @item.ConsumerInfo.ConsumerId
                    </td>
                    <td class="vertical-center">
                        @Html.ActionLink(@item.BrokerInfo.BrokerName, "Index", "Broker", new { clusterName = ViewBag.ClusterName, brokerName = @item.BrokerInfo.BrokerName }, null)
                    </td>
                    <td class="vertical-center">
                        @item.ConsumerInfo.Topic
                    </td>
                    <td class="text-center vertical-center">
                        @item.ConsumerInfo.QueueId
                    </td>
                    <td class="text-center vertical-center">
                        @item.ConsumerInfo.QueueCurrentOffset
                    </td>
                    <td class="text-center vertical-center">
                        @item.ConsumerInfo.ConsumedOffset
                    </td>
                    <td class="text-center vertical-center">
                        @item.ConsumerInfo.QueueNotConsumeCount
                    </td>
                    <td class="text-center vertical-center">
                        @item.ConsumerInfo.ClientCachedMessageCount
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

ENodeMicro/EQueue.AdminWeb/Views/Home/Index.cshtml
@model EQueue.AdminWeb.Models.ClusterListViewModel
@{
    ViewBag.Title = "ClusterList";
}
<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th width="80%" class="vertical-center">
                    集群名称
                </th>
                <th width="20%" class="vertical-center">
                    操作
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ClusterList)
            {
                <tr>
                    <td class="vertical-center">
                        @item
                    </td>
                    <td class="vertical-center">
                        @Html.ActionLink("查看Broker列表", "BrokerList", new { clusterName = item })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

ENodeMicro/EQueue.AdminWeb/Views/Home/ProducerList.cshtml
@model EQueue.AdminWeb.Models.ClusterProducerListViewModel
@{
    ViewBag.Title = "ProducerList";
}
<div>
    @using (Html.BeginForm("ProducerList", "Home", new { clusterName = ViewBag.ClusterName }, FormMethod.Post, null, new { @class = "form-inline header-form", role = "form" }))
    {
        <div class="form-group">
            <label class="sr-only" for="ClusterName"></label>
            @Html.TextBoxFor(m => m.ClusterName, new { @class = "form-control", placeholder = "ClusterName" })
        </div>
        <button type="submit" class="btn btn-default">查询</button>
    }
    <table class="table table-striped">
        <thead>
            <tr>
                <th width="20%" class="vertical-center">
                    BrokerName
                </th>
                <th width="80%" class="vertical-center">
                    ProducerId
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ProducerList)
            {
                foreach (var item in line.ProducerList)
                {
                    <tr>
                        <td class="vertical-center">
                            @Html.ActionLink(@line.BrokerInfo.BrokerName, "Index", "Broker", new { clusterName = ViewBag.ClusterName, brokerName = @line.BrokerInfo.BrokerName }, null)
                        </td>
                        <td class="vertical-center">
                            @item
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

ENodeMicro/EQueue.AdminWeb/Views/Home/QueueInfoList.cshtml
@model EQueue.AdminWeb.Models.ClusterTopicQueueListViewModel
@{
    ViewBag.Title = "QueueInfoList";
}
<style>
    .header-form {
        display: inline-block;
        float: left;
    }

    .next-form {
        margin-left: 15px;
    }
</style>
<div>
    @using (Html.BeginForm("QueueInfoList", "Home", new { clusterName = ViewBag.ClusterName }, FormMethod.Post, null, new { @class = "form-inline header-form", role = "form" }))
    {
        <div class="form-group">
            <label class="sr-only" for="ClusterName"></label>
            @Html.TextBoxFor(m => m.ClusterName, new { @class = "form-control", placeholder = "ClusterName" })
        </div>
        <div class="form-group">
            <label class="sr-only" for="Topic"></label>
            @Html.TextBoxFor(m => m.Topic, new { @class = "form-control", placeholder = "Topic" })
        </div>
        <button type="submit" class="btn btn-default">查询</button>
    }
    <table class="table table-striped">
        <thead>
            <tr>
                <th width="15%" class="vertical-center">
                    BrokerName
                </th>
                <th width="10%" class="vertical-center">
                    Topic
                </th>
                <th width="10%" class="text-center vertical-center">
                    QueueId
                </th>
                <th width="10%" class="text-center vertical-center">
                    CurrentOffset
                </th>
                <th width="10%" class="text-center vertical-center">
                    MinOffset
                </th>
                <th width="10%" class="text-center vertical-center">
                    消费进度
                </th>
                <th width="10%" class="text-center vertical-center">
                    堆积数
                </th>
                <th width="5%" class="text-center vertical-center">
                    A_S
                </th>
                <th width="5%" class="text-center vertical-center">
                    A_C
                </th>
                <th width="10%" class="text-center vertical-center">
                    发送TPS
                </th>
                <th width="5%" class="vertical-center">
                    操作
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.TopicQueueInfoList)
            {
                foreach (var item in line.TopicQueueInfoList)
                {
                    <tr>
                        <td class="vertical-center">
                            @Html.ActionLink(@line.BrokerInfo.BrokerName, "Index", "Broker", new { clusterName = ViewBag.ClusterName, brokerName = @line.BrokerInfo.BrokerName }, null)
                        </td>
                        <td class="vertical-center">
                            @item.Topic
                        </td>
                        <td class="text-center vertical-center">
                            @item.QueueId
                        </td>
                        <td class="text-center vertical-center">
                            @item.QueueCurrentOffset
                        </td>
                        <td class="text-center vertical-center">
                            @item.QueueMinOffset
                        </td>
                        <td class="text-center vertical-center">
                            @item.QueueMinConsumedOffset
                        </td>
                        <td class="text-center vertical-center">
                            @item.QueueNotConsumeCount
                        </td>
                        <td class="text-center vertical-center">
                            @item.ProducerVisible
                        </td>
                        <td class="text-center vertical-center">
                            @item.ConsumerVisible
                        </td>
                        <td class="text-center vertical-center">
                            @item.SendThroughput
                        </td>
                        <td class="vertical-center">
                            <div class="dropdown">
                                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                                    操作
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li>
                                        @Html.ActionLink("新增队列 For Cluster", "AddQueue", new { clusterName = ViewBag.ClusterName, topic = item.Topic })
                                    </li>
                                    <li>
                                        @if (item.ProducerVisible)
                                        {
                                            @Html.ActionLink("禁止发送 For Cluster", "SetQueueProducerVisible", new { clusterName = ViewBag.ClusterName, topic = item.Topic, queueId = item.QueueId, visible = !item.ProducerVisible })
                                        }
                                        else
                                        {
                                            @Html.ActionLink("允许发送 For Cluster", "SetQueueProducerVisible", new { clusterName = ViewBag.ClusterName, topic = item.Topic, queueId = item.QueueId, visible = !item.ProducerVisible })
                                        }
                                    </li>
                                    <li>
                                        @if (item.ConsumerVisible)
                                        {
                                            @Html.ActionLink("禁止消费 For Cluster", "SetQueueConsumerVisible", new { clusterName = ViewBag.ClusterName, topic = item.Topic, queueId = item.QueueId, visible = !item.ConsumerVisible })
                                        }
                                        else
                                        {
                                            @Html.ActionLink("允许消费 For Cluster", "SetQueueConsumerVisible", new { clusterName = ViewBag.ClusterName, topic = item.Topic, queueId = item.QueueId, visible = !item.ConsumerVisible })
                                        }
                                    </li>
                                    <li>@Html.ActionLink("删除队列 For Cluster", "DeleteQueue", new { clusterName = ViewBag.ClusterName, topic = item.Topic, queueId = item.QueueId })</li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>